USE learnsql;

-- p.143
SELECT GETDATE();                                      -- error
SELECT NOW();
SELECT SYSDATE FROM DUAL;                              -- error

-- p.145
SELECT DATE '2010-12-31' + INTERVAL '1' DAY;
SELECT DATE '2010-12-31' + INTERVAL '1' MONTH;

SELECT DATE_HIRE, DATEADD(MONTH, 1, DATE_HIRE)
	FROM EMPLOYEE_PAY_TBL;                              -- error
SELECT DATE_HIRE, ADD_MONTHS(DATE_HIRE, 1)
	FROM EMPLOYEE_PAY_TBL;                              -- error
SELECT DATE_HIRE, DATE_HIRE + 1
	FROM EMPLOYEE_PAY_TBL
    WHERE EMP_ID = '311549902';                         -- error
SELECT DATE_HIRE, DATE_ADD(DATE_HIRE, INTERVAL 1 DAY), DATE_HIRE + 1
	FROM EMPLOYEE_PAY_TBL
    WHERE EMP_ID = '311549902';
SELECT DATE_HIRE, DATE_ADD(DATE_HIRE, INTERVAL 2 MONTH)
	FROM EMPLOYEE_PAY_TBL
    WHERE EMP_ID = '311549902';
SELECT DATE_HIRE, DATE_ADD(DATE_HIRE, INTERVAL 3 YEAR)
	FROM EMPLOYEE_PAY_TBL
    WHERE EMP_ID = '311549902';

-- p.146
SELECT DATE_HIRE, DAYNAME(DATE_HIRE)
	FROM EMPLOYEE_PAY_TBL;
SELECT DATE_HIRE, DAYOFMONTH(DATE_HIRE)
	FROM EMPLOYEE_PAY_TBL;
SELECT DATE_HIRE, DAYOFWEEK(DATE_HIRE), DAYNAME(DATE_HIRE)
	FROM EMPLOYEE_PAY_TBL;
SELECT DATE_HIRE, DAYOFYEAR(DATE_HIRE)
	FROM EMPLOYEE_PAY_TBL;
    
-- p.149
SELECT DATE_HIRE = DATENAME(MONTH, DATE_HIRE)
	FROM EMPLOYEE_PAY_TBL;                                        -- error
SELECT DATE_HIRE, TO_CHAR(DATE_HIRE, 'Month dd, yyyy') HIRE
	FROM EMPLOYEE_PAY_TBL;                                        -- error

SELECT STR_TO_DATE('01/01/2010 12:00:00 AM', '%m/%d/%Y %h:%i:%s %p') AS FORM_DATE
	FROM EMPLOYEE_PAY_TBL;

-- p.150
SELECT CONVERT(DATETIME, '02/25/2010 12:00:00 AM') AS FORMAT_DATE
	FROM EMPLOYEE_PAY_TBL;                                       -- error