USE LEARNSQL;

-- p.156
SELECT EMPLOYEE_TBL.EMP_ID,
	   EMPLOYEE_PAY_TBL.DATE_HIRE
FROM EMPLOYEE_TBL,
	 EMPLOYEE_PAY_TBL
WHERE EMPLOYEE_TBL.EMP_ID = EMPLOYEE_PAY_TBL.EMP_ID;

-- p.157
SELECT EMPLOYEE_TBL.EMP_ID,
	EMPLOYEE_TBL.LAST_NAME,
    EMPLOYEE_PAY_TBL.POSITION
FROM EMPLOYEE_TBL,
	EMPLOYEE_PAY_TBL
WHERE EMPLOYEE_TBL.EMP_ID = EMPLOYEE_PAY_TBL.EMP_ID;

SELECT EMPLOYEE_TBL.EMP_ID,
	EMPLOYEE_PAY_TBL.DATE_HIRE
FROM EMPLOYEE_TBL
	INNER JOIN EMPLOYEE_PAY_TBL
ON EMPLOYEE_TBL.EMP_ID = EMPLOYEE_PAY_TBL.EMP_ID;

SELECT E.EMP_ID, 
	EP.SALARY, 
	EP.DATE_HIRE, 
    E.LAST_NAME
FROM EMPLOYEE_TBL E, 
	EMPLOYEE_PAY_TBL EP
WHERE E.EMP_ID = EP.EMP_ID
	AND EP.SALARY > 20000;
    
-- p.158
SELECT EMPLOYEE_TBL.EMP_ID,
	EMPLOYEE_PAY_TBL.DATE_HIRE
FROM EMPLOYEE_TBL,
	EMPLOYEE_PAY_TBL
WHERE EMPLOYEE_TBL.EMP_ID != EMPLOYEE_PAY_TBL.EMP_ID;

SELECT E.EMP_ID,
	E.LAST_NAME,
    P.POSITION
FROM EMPLOYEE_TBL E,
	EMPLOYEE_PAY_TBL P
WHERE E.EMP_ID <> P.EMP_ID;

-- p.159
SELECT P.PROD_DESC,
	O.QTY
FROM PRODUCTS_TBL P,
	ORDERS_TBL O
WHERE P.PROD_ID = O.PROD_ID;

SELECT P.PROD_DESC,
	O.QTY
FROM PRODUCTS_TBL P
	RIGHT OUTER JOIN ORDERS_TBL O
ON P.PROD_ID = O.PROD_ID;

-- p.160
SELECT P.PROD_DESC,
	O.QTY
FROM PRODUCTS_TBL P,
	ORDERS_TBL O
WHERE P.PROD_ID = O.PROD_ID(+);

SELECT P.PROD_DESC,
	O.QTY
FROM PRODUCTS_TBL P
	LEFT OUTER JOIN ORDERS_TBL O
ON P.PROD_ID = O.PROD_ID;

-- p.161
SELECT A.LAST_NAME,
	B.LAST_NAME,
    A.FIRST_NAME
FROM EMPLOYEE_TBL A,
	EMPLOYEE_TBL B
WHERE A.LAST_NAME = B.LAST_NAME;

SELECT A.LAST_NAME,
	B.LAST_NAME,
    A.FIRST_NAME
FROM EMPLOYEE_TBL A
	INNER JOIN EMPLOYEE_TBL B
ON A.LAST_NAME = B.LAST_NAME;

SELECT A.LAST_NAME,
	B.LAST_NAME,
    A.FIRST_NAME
FROM EMPLOYEE_TBL A,
	 EMPLOYEE_TBL B
WHERE A.LAST_NAME = B.LAST_NAME 
	AND A.FIRST_NAME != B.FIRST_NAME;

CREATE TABLE EMP                                   -- 创建表EMP
(
ID  CHAR(5)  NOT NULL,
NAME  VARCHAR(10)  NOT NULL,
MGR_ID  CHAR(5)
);

INSERT INTO EMP VALUES                             -- 给表EMP输入记录
	('1', 'JOHN', '0');
INSERT INTO EMP VALUES
	('2', 'MARY', '1');
INSERT INTO EMP VALUES
	('3', 'STEVE', '1');
INSERT INTO EMP VALUES
	('4', 'JACK', '2');
INSERT INTO EMP VALUES
	('5', 'SUE', '2');

SELECT * FROM EMP;

-- p.162
SELECT E1.NAME,
	E2.NAME
FROM EMP E1,
	EMP E2
WHERE E1.MGR_ID = E2.ID;

-- p.163
SELECT C.CUST_NAME,
	P.PROD_DESC
FROM CUSTOMER_TBL C,
	PRODUCTS_TBL P,
    ORDERS_TBL O
WHERE C.CUST_ID = O.CUST_ID
	AND P.PROD_ID = O.PROD_ID;

-- p.164
SELECT E.EMP_ID,
	E.LAST_NAME,
    P.POSITION
FROM EMPLOYEE_TBL E,
	EMPLOYEE_PAY_TBL P;