USE LEARNSQL;

-- 第1题
SELECT E.LAST_NAME,
	E.FIRST_NAME,
    EP.DATE_HIRE
FROM EMPLOYEE_TBL E,
	EMPLOYEE_PAY_TBL EP;
    
SELECT E.LAST_NAME,
	EP.DATE_HIRE,
	E.FIRST_NAME
FROM EMPLOYEE_TBL E,
	EMPLOYEE_PAY_TBL EP;

SELECT E.LAST_NAME,
	E.FIRST_NAME,
    EP.DATE_HIRE
FROM EMPLOYEE_PAY_TBL EP,
	EMPLOYEE_TBL E;
    
-- 第2题
SELECT E.LAST_NAME,
	E.FIRST_NAME,
    EP.DATE_HIRE
FROM EMPLOYEE_TBL E,
	EMPLOYEE_PAY_TBL EP
WHERE E.EMP_ID = EP.EMP_ID;

SELECT E.EMP_ID,
	E.LAST_NAME,
	E.FIRST_NAME,
    EP.DATE_HIRE
FROM EMPLOYEE_TBL E,
	EMPLOYEE_PAY_TBL EP
WHERE E.EMP_ID = EP.EMP_ID;

-- 第3题
SELECT E.LAST_NAME,
	E.FIRST_NAME,
    EP.DATE_HIRE
FROM EMPLOYEE_TBL E
	INNER JOIN EMPLOYEE_PAY_TBL EP
ON E.EMP_ID = EP.EMP_ID;

-- 第4题
SELECT E.EMP_ID,
	E.LAST_NAME,
    E.FIRST_NAME,
    EP.SALARY,
    EP.BONUS
FROM EMPLOYEE_TBL E
	INNER JOIN EMPLOYEE_PAY_TBL EP
ON E.EMP_ID = EP.EMP_ID;

SELECT E.EMP_ID,
	E.LAST_NAME,
    E.FIRST_NAME,
    EP.SALARY,
    EP.BONUS
FROM EMPLOYEE_TBL E,
	EMPLOYEE_PAY_TBL EP
WHERE E.EMP_ID = EP.EMP_ID;

SELECT E.CITY,
	AVG(EP.SALARY)
FROM EMPLOYEE_TBL E,
	EMPLOYEE_PAY_TBL EP
WHERE E.EMP_ID = EP.EMP_ID
GROUP BY CITY;

SELECT E.CITY,
	AVG(EP.SALARY)
FROM EMPLOYEE_TBL E
	INNER JOIN EMPLOYEE_PAY_TBL EP
ON E.EMP_ID = EP.EMP_ID
GROUP BY CITY;

-- 第5题
-- (略）