USE learnsql;

-- p.171
SELECT E.EMP_ID,
	E.LAST_NAME,
    E.FIRST_NAME,
    EP.PAY_RATE
FROM EMPLOYEE_TBL E,
	EMPLOYEE_PAY_TBL EP
WHERE E.EMP_ID = EP.EMP_ID
	AND EP.PAY_RATE < (SELECT PAY_RATE
					   FROM EMPLOYEE_PAY_TBL
                       WHERE EMP_ID = '443679012');

SELECT PAY_RATE
FROM EMPLOYEE_PAY_TBL
WHERE EMP_ID = '220984332';

SELECT E.EMP_ID,
	E.LAST_NAME,
    E.FIRST_NAME,
    EP.PAY_RATE
FROM EMPLOYEE_TBL E,
	EMPLOYEE_PAY_TBL EP
WHERE E.EMP_ID = EP.EMP_ID
	AND EP.PAY_RATE > (SELECT PAY_RATE
					   FROM EMPLOYEE_PAY_TBL
                       WHERE EMP_ID = '220984332');

-- p.172
CREATE TABLE RICH_EMPLOYEES
(
EMP_ID  VARCHAR(9)  NOT NULL,
LAST_NAME  VARCHAR(15)  NOT NULL,
FIRST_NAME  VARCHAR(15)  NOT NULL,
PAY_RATE  DECIMAL(4, 2)
);

INSERT INTO RICH_EMPLOYEES
SELECT E.EMP_ID,
	E.LAST_NAME,
    E.FIRST_NAME,
    EP.PAY_RATE
FROM EMPLOYEE_TBL E,
	EMPLOYEE_PAY_TBL EP
WHERE E.EMP_ID = EP.EMP_ID
	AND EP.PAY_RATE > (SELECT PAY_RATE
					   FROM EMPLOYEE_PAY_TBL
                       WHERE EMP_ID = '220984332');

SELECT DISTINCT * FROM RICH_EMPLOYEES;
SELECT * FROM RICH_EMPLOYEES;

SELECT EMP_ID
FROM EMPLOYEE_TBL
WHERE CITY = 'INDIANAPOLIS';

-- p.173
UPDATE EMPLOYEE_PAY_TBL
SET PAY_RATE = PAY_RATE * 1.1
WHERE EMP_ID IN (SELECT EMP_ID
				 FROM EMPLOYEE_TBL
                 WHERE CITY = 'INDIANAPOLIS');

SELECT * FROM EMPLOYEE_PAY_TBL;

UPDATE EMPLOYEE_PAY_TBL
SET PAY_RATE = PAY_RATE / 1.1
WHERE EMP_ID IN (SELECT EMP_ID
				 FROM EMPLOYEE_TBL
                 WHERE CITY = 'INDIANAPOLIS');

SELECT * FROM EMPLOYEE_PAY_TBL;

DELETE 
FROM EMPLOYEE_PAY_TBL
WHERE EMP_ID = (SELECT EMP_ID
			    FROM EMPLOYEE_TBL
                WHERE LAST_NAME = 'GLASS'
					AND FIRST_NAME = 'BRANDON');

INSERT INTO EMPLOYEE_PAY_TBL VALUES
('213764555','SALES MANAGER','2004-08-14',NULL,'2009-08-01','30000','2000');

-- p.174
SELECT CUST_ID,
	CUST_NAME
FROM CUSTOMER_TBL
WHERE CUST_ID IN (SELECT O.CUST_ID
				  FROM ORDERS_TBL O,
					  PRODUCTS_TBL P
				  WHERE O.PROD_ID = P.PROD_ID
					  AND O.QTY * P.COST > (SELECT SUM(COST)
											FROM PRODUCTS_TBL));

SELECT SUM(COST) FROM PRODUCTS_TBL;

SELECT O.CUST_ID
FROM ORDERS_TBL O,
	PRODUCTS_TBL P
WHERE O.PROD_ID = P.PROD_ID
	AND O.QTY * P.COST > 138.08;
    
SELECT CUST_ID,
	CUST_NAME
FROM CUSTOMER_TBL
WHERE CUST_ID IN (SELECT O.CUST_ID
				  FROM ORDERS_TBL O,
					  PRODUCTS_TBL P
				  WHERE O.PROD_ID = P.PROD_ID
					  AND O.QTY * P.COST > 138.08);

-- p.175
SELECT CUST_ID,
	CUST_NAME
FROM CUSTOMER_TBL
WHERE CUST_ID IN (287, 43);

SELECT C.CUST_NAME
FROM CUSTOMER_TBL C
WHERE 10 < (SELECT SUM(O.QTY)
			FROM ORDERS_TBL O
            WHERE O.CUST_ID = C.CUST_ID);

SELECT C.CUST_NAME,
	SUM(O.QTY)
FROM CUSTOMER_TBL C,
	ORDERS_TBL O
WHERE C.CUST_ID = O.CUST_ID
GROUP BY C.CUST_NAME;

-- p.176
SELECT CUST_ID,
	CUST_NAME
FROM CUSTOMER_TBL
WHERE CUST_ID IN (SELECT O.CUST_ID
				  FROM ORDERS_TBL O,
					  PRODUCTS_TBL P
				  WHERE O.PROD_ID = P.PROD_ID
					  AND O.QTY + P.COST < (SELECT SUM(COST)
											FROM PRODUCTS_TBL));