USE learnsql;

-- 第1题
-- (略）

-- 第2题
UPDATE CUSTOMER_TBL
SET CUST_NAME = 'DAVIDS MARKET'
WHERE CUST_ID = (SELECT CUST_ID
				 FROM ORDERS_TBL
                 WHERE ORD_NUM = '23E934');

SELECT * FROM CUSTOMER_TBL;

UPDATE CUSTOMER_TBL                                    -- 改回原名
SET CUST_NAME = 'SCOTTYS MARKET'
WHERE CUST_ID = (SELECT CUST_ID
				 FROM ORDERS_TBL
                 WHERE ORD_NUM = '23E934');

-- 第3题
SELECT LAST_NAME,
	FIRST_NAME,
    MIDDLE_NAME
FROM EMPLOYEE_TBL
WHERE EMP_ID IN (SELECT EMP_ID
			     FROM EMPLOYEE_PAY_TBL
                 WHERE PAY_RATE > (SELECT PAY_RATE 
								 FROM EMPLOYEE_PAY_TBL
                                 WHERE EMP_ID = '343559876'));

SELECT E.LAST_NAME,
	E.FIRST_NAME,
    E.MIDDLE_NAME
FROM EMPLOYEE_TBL E,
	EMPLOYEE_PAY_TBL P
WHERE E.EMP_ID = P.EMP_ID
	AND P.PAY_RATE > (SELECT PAY_RATE
					  FROM EMPLOYEE_PAY_TBL
					  WHERE EMP_ID = '343559876');

SELECT E.LAST_NAME,
	E.FIRST_NAME,
    E.MIDDLE_NAME
FROM EMPLOYEE_TBL E
INNER JOIN	EMPLOYEE_PAY_TBL P
ON E.EMP_ID = P.EMP_ID
WHERE P.PAY_RATE > (SELECT PAY_RATE
					  FROM EMPLOYEE_PAY_TBL
					  WHERE EMP_ID = '343559876');

-- 第4题
SELECT *
FROM PRODUCTS_TBL
WHERE COST > (SELECT AVG(COST)
			  FROM PRODUCTS_TBL);