USE learnsql;

-- 第1题
SELECT CUST_ID
FROM CUSTOMER_TBL
INTERSECT
SELECT CUST_ID
FROM ORDERS_TBL;

SELECT C.CUST_ID, C.CUST_NAME
FROM CUSTOMER_TBL C
WHERE C.CUST_ID IN (SELECT CUST_ID 
					FROM ORDERS_TBL O
                    WHERE C.CUST_ID = O.CUST_ID);

-- 第2题
SELECT CUST_ID
FROM CUSTOMER_TBL
EXCEPT
SELECT CUST_ID
FROM ORDERS_TBL;

SELECT CUST_ID
FROM CUSTOMER_TBL
MINUS
SELECT CUST_ID
FROM ORDERS_TBL;

SELECT C.CUST_ID, C.CUST_NAME
FROM CUSTOMER_TBL C
WHERE C.CUST_ID NOT IN (SELECT CUST_ID
						FROM ORDERS_TBL O
                        WHERE C.CUST_ID = O.CUST_ID);