use learnsql;

-- 第1题
-- a
SELECT EMP_ID,
	   LAST_NAME,
       FIRST_NAME
FROM EMPLOYEE_TBL
WHERE SUBSTRING(PHONE, 1, 3) = '317' OR 
	  SUBSTRING(PHONE, 1, 3) = '812' OR 
      SUBSTRING(PHONE, 1, 3) = '765'; 

SELECT EMP_ID,
	   LAST_NAME,
       FIRST_NAME
FROM EMPLOYEE_TBL
WHERE SUBSTRING(PHONE, 1, 3) IN ('317', '812', '765'); 

-- b
SELECT LAST_NAME,
	   FIRST_NAME
FROM EMPLOYEE_TBL
WHERE LAST_NAME LIKE 'WAL%';

-- c 
SELECT E.EMP_ID,
	   E.LAST_NAME,
       E.FIRST_NAME,
       EP.SALARY
FROM EMPLOYEE_TBL E,
	 EMPLOYEE_PAY_TBL EP
WHERE LAST_NAME LIKE 'S%'
  AND E.EMP_ID = EP.EMP_ID;
  
SELECT E.EMP_ID,
	   E.LAST_NAME,
       E.FIRST_NAME,
       EP.SALARY
FROM EMPLOYEE_TBL E
	 INNER JOIN EMPLOYEE_PAY_TBL EP
			    ON E.EMP_ID = EP.EMP_ID
WHERE LAST_NAME LIKE 'S%';

SELECT E.EMP_ID,
	   E.LAST_NAME,
       E.FIRST_NAME,
       EP.SALARY
FROM EMPLOYEE_TBL E,
	 EMPLOYEE_PAY_TBL EP
WHERE E.EMP_ID = EP.EMP_ID
  AND LAST_NAME LIKE 'S%';

-- 第2题
CREATE TABLE EMPLOYEE_PAYHIST_TBL
(
PAYHIST_ID  VARCHAR(9)  NOT NULL  primary key,
EMP_ID  VARCHAR(9)  NOT NULL,
START_DATE  DATETIME  NOT NULL,
END_DATE  DATETIME,
PAY_RATE  DECIMAL(4, 2)  NOT NULL,
SALARY  DECIMAL(8, 2)  NOT NULL,
BONUS  DECIMAL(8, 2)  NOT NULL,
CONSTRAINT EMP_FK_PAYHIST FOREIGN KEY (EMP_ID)
REFERENCES EMPLOYEE_TBL (EMP_ID));

-- a 
SELECT 'SALARIED EMPLOYEE' TYPE, COUNT(*)                -- error
FROM EMPLOYEE_PAYHIST_TBL EPH
     INNER JOIN EMPLOYEE_PAY_TBL EP ON EPH.EMP_ID = EP.EMP_ID
WHERE EP.SALARY IS NOT NULL
  AND EPH.END_DATE BETWEEN EPH.START_DATE AND DATE_ADD(EPH.START_DATE, INTERVAL 1 YEAR)
UNION ALL
SELECT 'NONSALARIED EMPLOYEE' TYPE, COUNT(*)
FROM EMPLOYEE_PAYHIST_TBL EPH
     INNER JOIN EMPLOYEE_PAY_TBL EP ON EPH.EMP_ID = EP.EMP_ID
WHERE EP.PAY_RATE IS NOT NULL
  AND EPH.END_DATE BETWEEN EPH.START_DATE AND DATE_ADD(EPH.START_DATE, INTERVAL 1 YEAR)
GROUP BY 1;

SELECT 'SALARIED EMPLOYEE' TYPE, COUNT(*)               -- error
FROM EMPLOYEE_PAYHIST_TBL EPH,
	 EMPLOYEE_PAY_TBL EP
WHERE EP.SALARY IS NOT NULL
  AND EPH.END_DATE BETWEEN EPH.START_DATE AND DATE_ADD(EPH.START_DATE, INTERVAL 1 YEAR)
  AND EPH.EMP_ID = EP.EMP_ID
UNION ALL
SELECT 'NONSALARIED EMPLOYEE' TYPE, COUNT(*)
FROM EMPLOYEE_PAYHIST_TBL EPH,
	 EMPLOYEE_PAY_TBL EP
WHERE EP.PAY_RATE IS NOT NULL
  AND EPH.END_DATE BETWEEN EPH.START_DATE AND DATE_ADD(EPH.START_DATE, INTERVAL 1 YEAR)
  AND EPH.EMP_ID = EP.EMP_ID
GROUP BY 1;

SELECT START_YEAR,
	   SUM(SALARIED) AS SALARIED,
       SUM(HOURLY) AS HOURLY
FROM (SELECT YEAR(E.START_DATE) AS START_YEAR,
			 COUNT(E.EMP_ID) AS SALARIED,
             0 AS HOURLY
	  FROM EMPLOYEE_PAYHIST_TBL E 
           INNER JOIN (SELECT MIN(START_DATE) START_DATE,
							  EMP_ID
					   FROM EMPLOYEE_PAYHIST_TBL
                       GROUP BY EMP_ID) F 
		   ON E.EMP_ID = F.EMP_ID AND E.START_DATE = F.START_DATE
	  WHERE E.SALARY > 0.00
      GROUP BY YEAR(E.START_DATE)
      UNION
      SELECT YEAR(E.START_DATE) AS START_YEAR,
			 0 AS SALARIED,
             COUNT(E.EMP_ID) AS HOURLY
	  FROM EMPLOYEE_PAYHIST_TBL E 
           INNER JOIN (SELECT MIN(START_DATE) START_DATE,
						      EMP_ID
					   FROM EMPLOYEE_PAYHIST_TBL
                       GROUP BY EMP_ID) F 
		   ON E.EMP_ID = F.EMP_ID AND E.START_DATE = F.START_DATE
	  WHERE E.PAY_RATE > 0.00
      GROUP BY YEAR(E.START_DATE)
      ) A 
GROUP BY START_YEAR
ORDER BY START_YEAR;

-- b 
SELECT START_YEAR,
	   SALARIED AS SALARIED,
       HOURLY AS HOURLY,
       (SALARIED - HOURLY) AS PAY_DIFFERENCE
FROM (SELECT YEAR(E.START_DATE) AS START_YEAR,
			 AVG(E.SALARY) AS SALARIED,
             0 AS HOURLY
	  FROM EMPLOYEE_PAYHIST_TBL E 
           INNER JOIN (SELECT MIN(START_DATE) START_DATE,
							  EMP_ID
					   FROM EMPLOYEE_PAYHIST_TBL
                       GROUP BY EMP_ID) F 
		   ON E.EMP_ID = F.EMP_ID AND E.START_DATE = F.START_DATE
	  WHERE E.SALARY > 0.00
      GROUP BY YEAR(E.START_DATE)
      UNION
      SELECT YEAR(E.START_DATE) AS START_YEAR,
			 0 AS SALARIED,
             AVG(E.PAY_RATE * 52 * 40) AS HOURLY
	  FROM EMPLOYEE_PAYHIST_TBL E 
           INNER JOIN (SELECT MIN(START_DATE) START_DATE,
						      EMP_ID
					   FROM EMPLOYEE_PAYHIST_TBL
                       GROUP BY EMP_ID) F 
		   ON E.EMP_ID = F.EMP_ID AND E.START_DATE = F.START_DATE
	  WHERE E.PAY_RATE > 0.00
      GROUP BY YEAR(E.START_DATE)
      ) A 
GROUP BY START_YEAR
ORDER BY START_YEAR;

-- c 
SELECT CURRENTPAY.EMP_ID,
	   STARTING_ANNUAL_PAY,
       CURRENT_ANNUAL_PAY,
       CURRENT_ANNUAL_PAY - STARTING_ANNUAL_PAY AS PAY_DIFFERENCE
FROM (SELECT EMP_ID,
			 (SALARY + (PAY_RATE * 52 * 40)) AS CURRENT_ANNUAL_PAY
	  FROM EMPLOYEE_PAYHIST_TBL
      WHERE END_DATE IS NULL) CURRENTPAY
     INNER JOIN 
     (SELECT E.EMP_ID,
			 (SALARY + (PAY_RATE * 52 * 40)) AS STARTING_ANNUAL_PAY
	  FROM EMPLOYEE_PAYHIST_TBL E
           INNER JOIN
           (SELECT MIN(START_DATE) START_DATE,
                   EMP_ID
		    FROM EMPLOYEE_PAYHIST_TBL
            GROUP BY EMP_ID) F 
	       ON E.EMP_ID = F.EMP_ID AND E.START_DATE = F.START_DATE
	  ) STARTINGPAY
      ON CURRENTPAY.EMP_ID = STARTINGPAY.EMP_ID;