USE learnsql;

-- 第2题 
SHOW TABLES;
SELECT NAME FROM SYS.TABLES;
SELECT * FROM USER_TABLES;

-- 第3题 
CREATE USER Steve IDENTIFIED BY 'Steve123';
GRANT SELECT ON learnsql.* TO Steve;

-- 第4题 
SELECT * FROM USER;
SELECT * FROM SYS.DATABASE_PRINCIPALS WHERE TYPE = 'S';
SELECT * FROM DBA_USERS;