USE LEARNSQL;

-- p.240
CREATE VIEW CUSTOMERS_VIEW AS
SELECT *
FROM CUSTOMER_TBL;

CREATE VIEW EMP_VIEW AS
SELECT LAST_NAME, FIRST_NAME, MIDDLE_NAME
FROM EMPLOYEE_TBL;

CREATE VIEW NAMES AS                -- OCACLE
SELECT LAST_NAME || ', ' ||FIRST_NAME || ' ' || MIDDLE_NAME NAME
FROM EMPLOYEE_TBL;

DROP VIEW NAMES;

CREATE VIEW NAMES AS
SELECT CONCAT(LAST_NAME, ', ', FIRST_NAME, ' ', MIDDLE_NAME) NAME     -- MIDDLE为null则NAME返回null
FROM EMPLOYEE_TBL;

CREATE VIEW NAMES AS
SELECT CONCAT(LAST_NAME, ', ', FIRST_NAME, ' ', IFNULL(MIDDLE_NAME, ' ')) NAME
FROM EMPLOYEE_TBL;

SELECT * 
FROM NAMES;

CREATE VIEW CITY_PAY AS
SELECT E.CITY, AVG(P.PAY_RATE) AVG_PAY
FROM EMPLOYEE_TBL E,
	 EMPLOYEE_PAY_TBL P 
WHERE E.EMP_ID = P.EMP_ID
GROUP BY E.CITY;

SELECT *
FROM CITY_PAY;

-- p.241
CREATE VIEW EMPLOYEE_SUMMARY AS
SELECT E.EMP_ID, E.LAST_NAME, P.POSITION, P.DATE_HIRE, P.PAY_RATE
FROM EMPLOYEE_TBL E,
	 EMPLOYEE_PAY_TBL P 
WHERE E.EMP_ID = P.EMP_ID;

SELECT *
FROM EMPLOYEE_SUMMARY;

-- p.242
CREATE VIEW EMPLOYEE_PAGERS AS
SELECT LAST_NAME, FIRST_NAME, PAGER
FROM EMPLOYEE_TBL
WHERE PAGER IS NOT NULL
WITH CHECK OPTION;

-- p.243
CREATE VIEW ACTIVE_CUSTOMERS AS
SELECT C.*
FROM CUSTOMER_TBL C,
	 ORDERS_TBL O 
WHERE C.CUST_ID = O.CUST_ID;

SELECT * 
FROM ACTIVE_CUSTOMERS;

CREATE TABLE CUSTOMER_ROSTER_TBL AS
SELECT CUST_ID, CUST_NAME
FROM ACTIVE_CUSTOMERS;

SELECT *
FROM CUSTOMER_ROSTER_TBL;

-- p.244
CREATE VIEW NAMES2 AS
SELECT LAST_NAME || ', ' || FIRST_NAME || ' ' || MIDDLE_NAME NAME
FROM EMPLOYEE_TBL
GROUP BY LAST_NAME || ', ' || FIRST_NAME || ' ' || MIDDLE_NAM;

CREATE VIEW NAMES2 AS
SELECT CONCAT(LAST_NAME, ', ', FIRST_NAME, ' ', IFNULL(MIDDLE_NAME, ' ')) NAME
FROM EMPLOYEE_TBL
GROUP BY 1;

SELECT *
FROM NAMES2;

-- p.246
CREATE SYNONYM CUST FOR CUSTOMER_TBL;
SELECT CUST_NAME FROM CUST;

CREATE SUNONYM PRODUCTS_TBL FOR USER1.PRODUCTS_TBL;

DROP SYNONYM CUST;