use learnsql;

-- 第1题
CREATE VIEW EMPO_VIEW AS
SELECT * FROM EMPLOYEE_TBL;

-- 第2题 
CREATE VIEW CITY_AVG_PAY AS
SELECT E.CITY, AVG(EP.SALARY), AVG(EP.PAY_RATE)
FROM EMPLOYEE_TBL E,
	 EMPLOYEE_PAY_TBL EP
WHERE E.EMP_ID = EP.EMP_ID
GROUP BY E.CITY;

SELECT *
FROM CITY_AVG_PAY;

-- 第3题 
CREATE VIEW CITY_AVG_PAY2 AS
SELECT E.CITY, AVG(EP.SALARY), AVG(EP.PAY_RATE)
FROM EMPO_VIEW E,
	 EMPLOYEE_PAY_TBL EP
WHERE E.EMP_ID = EP.EMP_ID
GROUP BY E.CITY;

SELECT *
FROM CITY_AVG_PAY2;

-- 第4题
CREATE TABLE EMPLOYEE_PAY_SUMMARIZED AS
SELECT * FROM CITY_AVG_PAY;

SELECT * INTO EMPLOYEE_PAY_SUMMARIZED FROM CITY_AVG_PAY;

SELECT * FROM EMPLOYEE_PAY_SUMMARIZED;

-- 第5题
DROP TABLE EMPLOYEE_PAY_SUMMARIZED;
DROP VIEW CITY_AVG_PAY2;
DROP VIEW CITY_AVG_PAY;
DROP VIEW EMPO_VIEW;