use learnsql;
use mysql;

-- p.258
DECLARE EMP_CURSOR CURSOR
FOR
SELECT * FROM EMPLOYEE_TBL;

OPEN EMP_CURSOR;

-- p.259
FETCH EMP_CURSOR INTO EMP_RECORD;

BEGIN
	 DECLARE done INT DEFAULT 0;
     DECLARE custname VARCHAR(30);
     DECLARE namecursor CURSOR FOR SELECT CUST_NAME FROM CUSTOMER_TBL;
     
	  OPEN namecursor;
      read_loop: LOOP
			FETCH namecursor INTO custname;
            IF done THEN
				  LEAVE read_loop;
		   END IF;
		  -- Do something with the variable
	  END LOOP;
      CLOSE namecursor;
END;

-- p.261
CREATE PROCEDURE NEW_PRODUCT
(PROD_ID IN  VARCHAR2, PROD_DESC IN VARCHAR2, COST IN NUMBER)
AS
BEGIN
  INSERT INTO PRODUCTS_TBL
  VALUES (PROD_ID, PROD_DESC, COST);
  COMMIT;
END;

-- p.262
CALL NEW_PRODUCT('9999', 'INDIAN CORN', 1.99);

-- p.265
SELECT CONCAT('GRANT ENABLE TO ', USER, ';')
FROM USER;

SHOW TABLES;
SELECT * FROM USER;

-- p.266
SELECT EMP_ID,
	   SALARY,
       RANK() OVER (PARTITION BY YEAR(DATE_HIRE)
					ORDER BY SALARY DESC) AS RANK_IN_DEPT
FROM EMPLOYEE_PAY_TBL;

SELECT EMP_ID, HIRE_DATE, SALARY
FROM EMPLOYEE_PAY_TBL
FOR XML AUTO;

SELECT EXTRACTVALUE('<a>Red</a><b>Blue<b/>', '/a') as ColorValue;