use learnsql;

DESC EMPLOYEE_PAY_TBL;

SELECT AVG(SALARY) FROM EMPLOYEE_PAY_TBL;

SELECT MAX(BONUS) FROM EMPLOYEE_PAY_TBL;

SELECT SUM(SALARY) FROM EMPLOYEE_PAY_TBL;

SELECT MIN(PAY_RATE) FROM EMPLOYEE_PAY_TBL;

SELECT COUNT(*) FROM employee_pay_tbl;