USE LEARNSQL;

INSERT INTO PRODUCTS_TBL VALUES
('11235','WITCH COSTUME','29.99');
INSERT INTO PRODUCTS_TBL VALUES
('222','PLASTIC PUMPKIN 18 INCH','7.75');
INSERT INTO PRODUCTS_TBL VALUES
('13','FALSE PARAFFIN TEETH','1.10');
INSERT INTO PRODUCTS_TBL VALUES
('90','LIGHTED LANTERNS','14.5');
INSERT INTO PRODUCTS_TBL VALUES
('15','ASSORTED COSTUMES','10.00');
INSERT INTO PRODUCTS_TBL VALUES
('9','CANDY CORN','1.35');
INSERT INTO PRODUCTS_TBL VALUES
('6','PUMPKIN CANDY','1.45');
INSERT INTO PRODUCTS_TBL VALUES
('87','PLASTIC SPIDERS','1.05');
INSERT INTO PRODUCTS_TBL VALUES
('119','ASSORTED MASKS','4.95');

SELECT * FROM PRODUCTS_TBL;

-- p.74，76
INSERT INTO PRODUCTS_TBL VALUES
('1234','KEY CHAIN','5.95');
INSERT INTO PRODUCTS_TBL VALUES
('2345','OAK BOOKSHELF','59.99');